# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/tbergq-graphql
  docker:
    - image: circleci/node:11

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/tbergq-graphql
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths: .
      - run: yarn test-ci
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/tbergq-graphql
      - run: yarn build
      - run: yarn deploy --token=$ZEIT_TOKEN

workflows:
  version: 2
  test-and-release:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master